project:
  type: website

website:
  title: Cancer Prediction in patients using Convolutional Neural Network, Logistic Regression, and Random Forest Algorithms
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-Fall25-101-201/final-project-taiwo-osunrinde-solo # Need to change to your project repo   
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: auto
